Lesson18/badges
arbaev/TestGuru pull request #17
Opened 2019-03-01 08:50 UTC by arbaev

2019-03-01 16:35 UTC, iBublik requested changes

2019-03-01 16:35 UTC, iBublik commented on TestGuru.xml
> +<mxfile modified="2019-02-26T07:57:49.552Z" host="www.draw.io" agent="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0" version="10.2.8" etag="1I7KHtUhJ1x1EfXyAQv4"><diagr
Что это?

2019-03-01 16:35 UTC, iBublik commented on app/assets/javascripts/badges_form.js
> +    if (this.value == "first_try") {
Перепиши на `case`

2019-03-01 16:35 UTC, iBublik commented on app/assets/javascripts/badges_form.js
> +function setOptions(items_array, select) {
```suggestion
function setOptions(itemsArray, select) {
```

2019-03-01 16:35 UTC, iBublik commented on app/controllers/application_controller.rb
> +  def expire_hsts
Что это?

2019-03-01 16:35 UTC, iBublik commented on app/controllers/test_passages_controller.rb
> +      UserBadgeService.new(@test_passage).give_badges if @test_passage.successful?
То что бейджи выдаются только при успещном прохождении - это нюанс реализации, который надо скрыть в сервисе

2019-03-01 16:35 UTC, iBublik commented on app/helpers/tests_helper.rb
> +    {0 => I18n.t('helpers.test.easy'),
Если у тебя упорядоченные ключи, то проще массив использовать

2019-03-01 16:35 UTC, iBublik commented on app/models/badge.rb
> +    %i[first_try all_category all_level].map { |item| [I18n.t("admin.badges.#{item}"), item] }
Переводы лучше в модель не пихать, это не ее задача. Можно в хелпер вынести, а в модели только возможные типы оставить
Кстати, в рельсе есть удобная штука - enum, как раз для таких случаев

2019-03-01 16:35 UTC, iBublik commented on app/services/user_badge_service.rb
> +      @user.badges.push(badge) if send(badge.criterion.to_sym, badge.param.to_i)
Лучше не выдавай бейджи, а просто возвращай список. Его намного проще переиспользовать - можно выдать, послать письмом или вывести на странице. А присвоение можно сделать в контроллере, все достаточно тривиально

2019-03-01 16:35 UTC, iBublik commented on app/services/user_badge_service.rb
> +  def all_level(level_id)
Методы-предикаты принято называть со знаком вопроса в конце

2019-03-01 16:35 UTC, iBublik commented on app/services/user_badge_service.rb
> +    level_tests_ids = Test.where(level: level_id).ids
Можно избежать запросов в базу, если сначала сравнить нужный уровень с уровнем текущего теста

2019-03-01 16:35 UTC, iBublik commented on app/services/user_badge_service.rb
> +    (level_tests_ids - @user.tests.ids).empty?
Вариант с загрузкой id неплох, но можно же просто число сравнивать. Главное считать только _уникальные_ тесты, т.к. у нас нет запрета на повторное прохождение теста

2019-03-01 16:35 UTC, iBublik commented on app/services/user_badge_service.rb
> +    (level_tests_ids - @user.tests.ids).empty?
Из задания:
> Выдать бэйдж после _успешного прохождения_ всех тестов определённого уровня

Нужно считать только успешно пройденные тесты
Подсказка - проще всего будет кешировать результат теста в базу при его прохождении. Тогда можно запросом выбрать только успешные прохождения

2019-03-01 16:35 UTC, iBublik commented on app/services/user_badge_service.rb
> +  def all_category(category_id)
Здесь все аналогично комментариям к all_level

2019-03-01 16:35 UTC, iBublik commented on app/services/user_badge_service.rb
> +      @user.badges.push(badge) if send(badge.criterion.to_sym, badge.param.to_i)
Не надо здесь параметр к числу приводить, пускай этим занимается конкретний метод-предикат. Не во всех правилах нужно число

2019-03-01 16:35 UTC, iBublik commented on app/services/user_badge_service.rb
> +  def first_try(test_id)
Как-то жестоко заставлять админа на каждый тест создавать новый такой бейдж. Это правило можно оставить вообще без параметра (неиспользуемые переменные в ruby принято начинать с подчеркивания)

2019-03-01 16:35 UTC, iBublik commented on app/views/admin/badges/_form.html.erb
> +  <%= content_tag :div, id: "data-categories", data: {categories: @categories.pluck(:id, :title)} do %>
Можно было отрендерить отдельный select для каждого типа ресурса. А на клиенте просто скрывать/показывать нужные. Чтоб отправлялся только 1 параметр (хотя селекта с одним именем будет 3), указывай disable на ненужных контролах

2019-03-01 16:35 UTC, iBublik commented on app/views/admin/badges/_form.html.erb
> +  <%= content_tag :div, id: "data-categories", data: {categories: @categories.pluck(:id, :title)} do %>
В принципе можешь свой вариант оставить, тут как тебе больше нравится

2019-03-01 17:05 UTC, arbaev commented on TestGuru.xml
> +<mxfile modified="2019-02-26T07:57:49.552Z" host="www.draw.io" agent="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0" version="10.2.8" etag="1I7KHtUhJ1x1EfXyAQv4"><diagr
ER-диаграмма, обновил

2019-03-01 17:06 UTC, arbaev commented on app/controllers/application_controller.rb
> +  def expire_hsts
отключение hsts для heroku

2019-03-02 17:06 UTC, arbaev commented on app/services/user_badge_service.rb
> +  def all_level(level_id)
в данном случае это усложнило вызов

2019-03-02 18:12 UTC, arbaev commented on app/services/user_badge_service.rb
> +  def first_try(test_id)
Добавил опцию "любой тест"

2019-03-03 12:45 UTC, iBublik requested changes

2019-03-03 12:45 UTC, iBublik commented on TestGuru.xml
> +<mxfile modified="2019-02-26T07:57:49.552Z" host="www.draw.io" agent="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0" version="10.2.8" etag="1I7KHtUhJ1x1EfXyAQv4"><diagr
А зачем ее тут в таком виде держать? Этот xml никому не интересен в диффах. Лучше как картинку или просто как ссылку в вики

2019-03-03 12:45 UTC, iBublik commented on app/controllers/test_passages_controller.rb
> +      @test_passage.user.badges.push(new_badges) if new_badges
Зачем эта проверка? Если сервис вернул пустой массив, то пользователю не будет ничего выдаваться

2019-03-03 12:45 UTC, iBublik commented on app/models/test.rb
> +  enum levels: %i[easy elementary advanced hard pro]
В чем суть использования enum здесь? Обычной константы хватит

2019-03-03 12:45 UTC, iBublik commented on app/services/user_badge_service.rb
>      badges = Badge.all
Зачем использовать лишнюю переменную?

2019-03-03 12:45 UTC, iBublik commented on app/services/user_badge_service.rb
> +    test_id.to_i == @test.id && not_passed_before?(@test)
`(test_id.to_i.zero? || test_id.to_i == @test.id) && not_passed_before?(@test)`

2019-03-03 12:45 UTC, iBublik commented on app/services/user_badge_service.rb
> +    @user.test_passages.select(&:successful?)
Я все же предлагаю тебе попробовать сделать без загрузки test_passage в память. Там вообще не сложно получится
Ну или сделай здесь хотя бы кеширование результата. Иначе у тебя для каждого бейджа заново тащятся из базы прохождения теста пользователем (классическая N+1 проблема)

2019-03-03 12:45 UTC, iBublik commented on app/services/user_badge_service.rb
> +      (cat_tests_ids - user_tests_successful.ids).empty?
`user_tests_successful` возвращает массив, у него нет метода ids

2019-03-04 17:45 UTC, max-underthesun commented on app/services/user_badge_service.rb
> +    @user.test_passages.where("result >= ?", TestPassage::SUCCESS_VALUE).map(&:test_id)
если тебе нужны только `test_id`, то зачем тащить полностью объекты из базы?
вместо `map` можно использовать `pluck` и база вернет только набор `test_id`

2019-03-04 17:45 UTC, max-underthesun commented on app/services/user_badge_service.rb
> +      level_tests_ids = Test.where(level: level_id.to_i).ids
`where`, `find` и т.п. принимают аргументом в качестве "ай-ди" как число, так и строку
нет нужды писать `.where(level: level_id.to_i)`, можно просто `.where(level: level_id)`

2019-03-04 17:45 UTC, max-underthesun commented on app/services/user_badge_service.rb
> +      (level_tests_ids - successful_user_tests_ids).empty?
вычитание массивов для проверки их равенства не всегда правильный прием
к примеру:
```ruby
2.5.1 :010 > [1, 1, 1, 2, 3, 3, 3] - [2, 3, 3, 1, 2]
 => []
```
в текущем случае, вроде бы нет подвохов и твой вариант должен работать (можешь оставить)

но я бы все равно предерживался более строгих записей - они несут больше информации о намереньях
сразу понятно что проверяется - равенство коллекций
и явно прописаны дополнительные условия - коллекции сортируются и фильтруются от дублей
что-то типа:
```ruby
level_tests_ids.sort.uniq == successful_user_tests_ids.sort.uniq
```
а еще правильней сортировку и фильрацию дублей сделать при вытаскивании из базы с помощью `order(:id)` и `distinct`

2019-03-04 17:45 UTC, max-underthesun commented on app/services/user_badge_service.rb
> +    end
см. комменты к предыдущему методу

2019-03-04 17:45 UTC, max-underthesun commented on app/services/user_badge_service.rb
> +    (test_id.to_i.zero? || test_id.to_i == @test.id) && not_passed_before?(@test)
я понимаю, что тут проверяется
но я не могу понять зачем первая проверка (скобки) нужна... )))

2019-03-04 17:45 UTC, max-underthesun commented on app/models/test.rb
> +  LEVELS = %i[easy elementary advanced hard pro]
мутабельные объекты нужно "фризить" в константах
ты до сих пор кодишь без линтера?
он такие вещи подсказывает

2019-03-04 17:45 UTC, max-underthesun commented on app/models/badge.rb
> +  validates :name, :image_url, :criterion, :param, presence: true
валидации рекомендуют писать после ассоциаций

2019-03-04 17:45 UTC, max-underthesun commented on app/models/test_passage.rb
> +  before_save :calc_result, if: :completed?
еще обновление аттрибута `result` можно сделать в методе `accept!`
именно там меняется результат теста (принимается очередной ответ)
коллбеками желательно сильно не увлекаться
- они затрудняют чтение кода
- усложняют использование модели, могут вызываться когда не надо (это ведет к появлению условных коллбеков - код еще более усложняется)
- могут создавать проблемы при тестировании

2019-03-04 17:48 UTC, arbaev commented on app/services/user_badge_service.rb
> +    @user.test_passages.where("result >= ?", TestPassage::SUCCESS_VALUE).map(&:test_id)
потому что Семён Семёныч! 😄

2019-03-06 09:43 UTC, merged