Lesson03/migrations
arbaev/TestGuru pull request #2
Opened 2018-12-21 11:54 UTC by arbaev

2018-12-21 16:54 UTC, iBublik requested changes

2018-12-21 16:54 UTC, iBublik commented on app/models/answer.rb
> +  belongs_to :question
С этим ты поспешил - ассоциации тема следующего урока. Можешь оставить, если понимаешь как они работают

2018-12-21 16:54 UTC, iBublik commented on db/migrate/20181221112644_change_null_constraint.rb
> +    change_column_null(:questions, :body, false)
Вопрос без теста вряд ли имеет смысл. Как и ответ без вопроса :)

2018-12-21 16:54 UTC, iBublik commented on db/migrate/20181221114605_add_tests_level_default.rb
> +    change_column_default(:tests, :level, 0)
Дефолты тоже можно было в одной миграции изменить

2018-12-21 16:54 UTC, iBublik commented on db/migrate/20181221141252_add_tests_level_default_reversible.rb
> +    change_column_default(:tests, :level, from: nil, to: 0)
Зачем по второму кругу? По идее ничего упасть не должно, но это избыточно

2018-12-21 16:54 UTC, iBublik commented on db/schema.rb
> +    t.boolean "correct", default: false
Для логических полей рекомендуется указывать опцию `null: false`. Тогда в базе будет строго 2 значения (true/false) вместо 3 (true/false/null)

2018-12-21 18:03 UTC, arbaev commented on app/models/answer.rb
> +  belongs_to :question
Вот это да! А я перелопатил кучу доков, изучал, как это делается. Ведь таблица без ассосиаций — деньги на ветер. Или что там? Ну, в общем, не то.
Наверно, стоит в задании указать для таких как я, что пока без связей работаем.

2018-12-21 18:08 UTC, arbaev commented on db/migrate/20181221141252_add_tests_level_default_reversible.rb
> +    change_column_default(:tests, :level, from: nil, to: 0)
А это я сначала сделал первый вариант и накатил его. А потом погулял, поразмышлял, дочитал доки и сделал вариант с откатом. В той же доке прочитал, что накатаные миграции лучше не трогать, а сделать ещё одну. Вот и сделал.

2018-12-21 18:09 UTC, arbaev commented on db/schema.rb
> +    t.boolean "correct", default: false
Ухты, не знал такого. С миграциями мне ещё много узнать предстоит, тема довольно обширная.

2018-12-21 18:14 UTC, arbaev commented on db/migrate/20181221114605_add_tests_level_default.rb
> +    change_column_default(:tests, :level, 0)
Про миграции урок весьма скудный :-( Не раздуплил ещё бест практикс

2018-12-22 06:33 UTC, iBublik commented on db/migrate/20181221141252_add_tests_level_default_reversible.rb
> +    change_column_default(:tests, :level, from: nil, to: 0)
@arbaev это правило действует на миграции, которые уже попали в продакшен (читай в мастер-ветку). Пока они в ветке с фичей, с ними можно что угодно сделать

2018-12-22 12:03 UTC, max-underthesun commented on db/migrate/20181222094014_set_default.rb
> +    change_column_default(:answers, :correct, false)
в [документации](https://edgeguides.rubyonrails.org/active_record_migrations.html#changing-columns) рекомендуют записывать миграцию смены "дефолта" как в 3-ей строке
вариант без `from:` и `to:` работает, его нельзя откатить (он `irreversible`) - лучше все миграции (по возможности) делать "откатываемыми"

2018-12-22 12:40 UTC, merged