Lesson06/validations
arbaev/TestGuru pull request #5
Opened 2019-01-09 20:29 UTC by arbaev

2019-01-09 20:34 UTC, arbaev commented on app/models/test.rb
> +  scope :hard, -> { where(level: 5..Float::INFINITY) }
А в Ruby 2.6 уже можно не указывать INFINITY 😉

2019-01-10 06:06 UTC, iBublik requested changes

2019-01-10 06:06 UTC, iBublik commented on app/models/category.rb
> +  default_scope { order(title: :asc) }
Скоуп по умолчанию меняет поведение всех запросов к этой модели. Это важное изменение, которое стоит держать на виду - перенеси в самый верх класса

2019-01-10 06:06 UTC, iBublik commented on app/models/question.rb
> +  validates :answers, length: { minimum: 1, maximum: 4 }
При создании ответа валидации вопроса не вызываются. Стоит это проверять именно в модели ответа. Учти, что валидация не должна мешать изменять ответы, даже если у вопроса их набралось 4

2019-01-10 06:06 UTC, iBublik commented on app/models/test.rb
> +  validates :title, uniqueness: { scope: :level }
Можно описать несколько валидаций одной командой - `validates :title, presence: true, uniqueness: ...`

2019-01-10 06:06 UTC, iBublik commented on app/models/test.rb
> +  validates :level, numericality: { only_integer: true, greater_than: -1 }
С точки зрения логики будет одинаково, но с точки зрения семантики понятнее будет на 0 проверять - `greater_than_or_equal_to: 0`

2019-01-10 06:06 UTC, iBublik commented on app/models/test.rb
> +  scope :hard, -> { where(level: 5..Float::INFINITY) }
Можешь использовать его, если с рельсами работает как надо

2019-01-10 06:06 UTC, iBublik commented on app/models/test.rb
> +  scope :difficulty, ->(difficulty) { public_send difficulty }
Не вижу профита в этом методе. Без него - `Test.easy`, с ним - `Test.difficulty(:easy)`, т.е. еще и печатать больше. При этом он может вызвать абсолютно любой публичный метод класса - `Test.difficulty(:count)`

2019-01-10 06:06 UTC, iBublik commented on app/models/test.rb
> +  scope :by_category, lambda { |cat|
У скоупов есть особенность - они должны возвращать chainable объект, чтоб можно было строить цепочки вызовов `where(level: ...).order(id: :desc).created_last_week ...`
Все методы-запросы как раз такие объекты возвращают. Но pluck вернет обычный массив, что нарушит этот принцип. Такое лучше делать обычными методами класса

2019-01-10 06:06 UTC, iBublik commented on db/migrate/20190109190945_change_null_to_user.rb
> +    change_column_null :users, :email, false
Чтоб не плодить миграции, можно сразу делать поле not null - `add_column ..., null: false`

2019-01-10 06:06 UTC, iBublik commented on app/models/test.rb
> +  validates :title, uniqueness: { scope: :level }
Чтоб валидация на уникальность была "настоящей", следует добавить уникальный индекс на уровне базы.

2019-01-10 07:12 UTC, arbaev commented on app/models/test.rb
> +  scope :by_category, lambda { |cat|
Делал строго по заданию, а оно, оказывается, проверяло на стойкость принципов :sweat_smile:

2019-01-10 09:02 UTC, arbaev commented on app/models/test.rb
> +  scope :difficulty, ->(difficulty) { public_send difficulty }
Ясно, я не точно понял задание.

2019-01-10 18:01 UTC, max-underthesun commented on db/migrate/20190110091915_add_index_to_tests_title.rb
> +end
не совсем верная миграция
у тебя же уникальность в скоупе нужна
поэтому, правильно примерно таким образом:

```ruby
class AddIndexToTests < ActiveRecord::Migration[5.2]
  def change
    add_index :tests, [:title, :level], unique: true
  end
end
```

2019-01-10 18:43 UTC, merged