Lesson10/sessions
arbaev/TestGuru pull request #9
Opened 2019-01-27 21:50 UTC by arbaev

2019-01-28 09:02 UTC, iBublik requested changes

2019-01-28 09:02 UTC, iBublik commented on app/controllers/sessions_controller.rb
> +    cookies.clear
Если сессия - обычно что-то персонализированное и ее вполне можно чистить после разлогинивания, то куки не стоит. Там может храниться всякая общая инфа, вроде города пользователя, которую не хочется терять после выхода из аккаунта

2019-01-28 09:02 UTC, iBublik commented on app/helpers/sessions_helper.rb
> +  def flash_message
Этот хелпер задумывался исключительно для вывода одного флеша. Если выводить множество, то это удобнее через паршл сделать - разметка в хелперах выглядит очень топорно

2019-01-28 09:02 UTC, iBublik commented on app/helpers/sessions_helper.rb
> +      result = ""
Вообще когда нужно свернуть коллецию, используют `reduce`
А тут можно было применить `map` + `safe_join`

2019-01-28 09:02 UTC, iBublik commented on app/helpers/sessions_helper.rb
> +      render inline: result
Делать render внутри хелпера избыточно. Достаточно вернуть результат, шаблон уже сам его отрендерит при использовании `<%= %>`

2019-01-28 09:02 UTC, iBublik commented on app/controllers/tests_controller.rb
> +    @test.author = current_user
`current_user.authorship.build(test_params)`
Только название ассоциации странное - почему там единственное число?

2019-01-28 09:02 UTC, iBublik commented on config/routes.rb
> +    get :start, on: :member
Зачем этот роут?

2019-01-28 09:02 UTC, iBublik commented on app/models/user.rb
> +  validates :email, format: { with: /.+@.+\..+/i },
Регулярка на грани фола - довольно сложно читается. В целом сложные регулярка бесполезны для валидации почты - https://davidcel.is/posts/stop-validating-email-addresses-with-regex/

2019-01-28 09:28 UTC, arbaev commented on app/models/user.rb
> +  validates :email, format: { with: /.+@.+\..+/i },
Ха, я именно этой статьёй и руководствовался! Подумал, что `/@/` будет слишком просто и поставил более продвинутый вариант оттуда же.

2019-01-28 09:33 UTC, arbaev commented on app/helpers/sessions_helper.rb
> +  def flash_message
Понятно. Хотел сделать универсальный вариант и пришлось немного покостылять.

2019-01-28 09:35 UTC, arbaev commented on app/helpers/sessions_helper.rb
> +      render inline: result
В данном случае это не работает, так как html экранируется и строка выводится как текст  <p class="flash flash-alert">Log in, please.</p>

2019-01-28 09:39 UTC, arbaev commented on app/helpers/sessions_helper.rb
> +      result = ""
И я хотел это сделать редьюсом, но его нет )) 
Про `map+safe_join` не догадался, будут иметь в виду теперь.

2019-01-28 09:44 UTC, arbaev commented on config/routes.rb
> +    get :start, on: :member
Это используется для возврата незалогиненного пользователя обратно в тест после логина.
При нажатии кнопки Start Test отправляется POST запрос. А редирект делается GET запросом.
Придумался такой способ 😷

2019-01-28 09:52 UTC, arbaev commented on app/controllers/tests_controller.rb
> +    @test.author = current_user
Да… просто не подумал, что правильно назвать АВТОРСТВЫ

2019-01-28 11:41 UTC, iBublik commented on app/helpers/sessions_helper.rb
> +      result = ""
reduce есть на всех коллекциях, где есть each

2019-01-28 11:42 UTC, iBublik commented on app/helpers/sessions_helper.rb
> +      render inline: result
Ну это потому что ты собрал "небезопасную" строку. Если сделать result.html_safe, то все будет ок

2019-01-28 11:43 UTC, iBublik commented on config/routes.rb
> +    get :start, on: :member
Правильнее будет запоминать в куки только GET запросы

2019-01-28 11:43 UTC, iBublik commented on app/models/user.rb
> +  validates :email, format: { with: /.+@.+\..+/i },
Ну это можно оставить, не знал что ты уже знаком со статьей :)

2019-01-29 05:13 UTC, iBublik commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!
Это проще вынести в ApplicationController, а где не требуется - сделать `skip_before_action`

2019-01-29 05:13 UTC, iBublik commented on app/controllers/sessions_controller.rb
> +    user = User.find_by(email: params[:email].downcase!)
Бессмысленное применение бэнг-метода. Так делают, когда нужно изменить объект "на месте":
```ruby
str = 'HI'
str.downcase!
puts str # 'hi'

str2 = 'HI'
str2.downcase # 'hi'
puts str2 # 'HI'
```
Т.е. без `!` создается копия объекта с изменениями. В данном случае этот вариант очевиднее - ты не меняешь входящие параметры, а просто создаешь копию с изменениям.

А вообще под это стоит выделить метод модели и делать приведение строк к нужному регистру там

2019-01-29 05:13 UTC, iBublik commented on app/helpers/sessions_helper.rb
> +      messages = flash.reduce("") do |acc, (name, msg)|
Ранее писал, что надо избегать работы с разметкой в хелперах - тяжело читается. То же самое, но намного проще https://stackoverflow.com/a/9392649

2019-01-29 05:13 UTC, iBublik commented on app/models/user.rb
> +    email.downcase!
Очень неявное изменение, не каждый поймет что ты поменял регистр. Лучше так `self.email = email.dowcnase`

2019-01-29 17:31 UTC, arbaev commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!
Безопаснее поддерживать whilte-list.
Эх, ну ладно...

2019-01-29 17:40 UTC, merged